### ISSUE TITLE
Does not render within wordpress page correctly

### ISSUE THREAD

**Issue by metaperl** [yewang/besogo#25]
Although a minimal HTML file renders fine in Besogo - http://static.livingcosmos.org/cdn/besogo/mydex.html

An attempt to embed this same HTML within a wordpress site leads to a black board and large buttons - http://www.metalevel.link/baduk/thequietcenter-vs-turkeytoprak/

**Comment by yewang** [comment]
Are you able to link to custom CSS from your wordpress site? It seems that the BesoGo stylesheets are missing for the page on the second link.

Try adding something like this (with paths adjusted to point to a place where they are hosted):
```
<link rel="stylesheet" type="text/css" href="css/besogo.css">
<link rel="stylesheet" type="text/css" href="css/board-wood.css" id="theme">
```

From the browser developer console, it appears that adding these stylesheets manually resolves the issue.
