### ISSUE TITLE
Is there an API?

### ISSUE THREAD

**Issue by Emanuel-de-Jong** [yewang/besogo#28]
Is it possible to control the board trough javascript code instead of the visual panels without changing the library code itself?
Something like `besogo.playMove(1, 2, 0);`

**Comment by yewang** [comment]
There is no formal API, but it is possible to interact with the editor and/or gameRoot objects to manipulate the editor or game tree state via javascript.

[Josekle](https://github.com/okonomichiyaki/josekle) and [Fusekle](https://github.com/yewang/fusekle) are examples of projects that do so.

For convenience, I've just made a [commit](https://github.com/yewang/besogo/commit/499b974dce1065e613b7b0da39ba3b4f953968f6) (porting the similar changes made by Josekle and Fusekle) that exposes the editor object via a reference attached to the parent container.

**Comment by Emanuel-de-Jong** [comment]
That will do.
Thank you!
